name: polaris-challenge-a3fe
channels:
  - conda-forge
  - openbiosim/label/dev
  - michellab/label/dev
  - defaults
dependencies:
  - arviz
  - pandas
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - scipy
  - ipython
  - pymbar[version='<4']
  - ambertools
  - biosimspace[version='>2023.4']
  - pydantic
  - polaris=0.11.8
  - ca-certificates
  - certifi
  - openssl
  - cuda-version=12.5
  - pymol-open-source
  - openeye-toolkits
  - pip:
      - git+https://github.com/michellab/a3fe.git
